server:
  port: ${PORT_PLATFORM_SYSTEM:8201}

spring:
  profiles:
    active: ${RUN_MODE:local}
  application:
    name: platform-system

  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:192.168.33.10}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}

  config:
    import:
      - nacos:global-configuration.yaml?refresh=true
      - nacos:tomcat.yaml
      - nacos:openfeign.yaml
      - nacos:hikari.yaml
      - nacos:rabbitmq.yaml
      - nacos:redis.yaml
      - nacos:mybatis-plus.yaml
      - nacos:jasypt.yaml
      - nacos:system-dict.yaml
      - nacos:minio.yaml
      - nacos:xxl-job.yaml
      - nacos:platform-system-rabbit-mq-queue.yaml
      - nacos:db-merge.yaml
      - nacos:sa-token.yaml

  aop:
    proxy-target-class: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  freemarker:
    check-template-location: false

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:192.168.33.10}:${DATASOURCE_PORT:3306}/${spring.cloud.nacos.config.namespace}_platform_system?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  type-aliases-package: com.zclcs.platform.system.api.entity
  mapper-locations: classpath:com/zclcs/platform/system/mapper/*.xml