logging:
  level:
    com.zclcs: info
    p6spy: info
    nacos.client: info
    com.alibaba: info
    com.zaxxer: info
    com.baomidou: info
    com.xxl.job: info
    org.springframework: info
    _org.springframework: info
    org.jboss: info
    org.hibernate: info
    org.mybatis: info
    org.apache: info
    io.netty: info
    org.redisson: info
    reactor.netty: info
    com.rabbitmq: info