server:
  port: ${PORT_CONFIG_SYNC:7102}
spring:
  profiles:
    active: ${RUN_MODE:local}
  application:
    name: third-part-config-sync

  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
