server:
  port: ${PORT_KNIFE4J:8401}

spring:
  security:
    user:
      name: ${KNIFE4J_USERNAME:zclcs}
      password: ${KNIFE4J_PASSWORD:123456}

knife4j:
  # 开启聚合组件
  enableAggregation: ${DOC_ENABLE_AGGREGATION:true}
  cloud:
    enable: true
