server:

  port: ${PORT_PLATFORM_GATEWAY:8301}

spring:

  main:
    allow-bean-definition-overriding: true

  application:
    name: platform-gateway

  config:
    import:
      - nacos:global-configuration.yaml?refresh=true
      - nacos:rabbitmq.yaml
      - nacos:redis.yaml
      - nacos:jasypt.yaml
      - nacos:swagger-${spring.profiles.active}.yaml
      - nacos:platform-system-rabbit-mq-queue.yaml

  cloud:

    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}

    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true

# spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
      client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      scope: server
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs
        - /actuator/**
