server:

  port: ${PORT_GATEWAY:8301}

spring:

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    allow-bean-definition-overriding: true

  application:
    name: platform-gateway

  config:
    import:
      - nacos:global-configuration.yaml
      - nacos:rabbitmq.yaml
      - nacos:redis.yaml
      - nacos:jasypt.yaml

  cloud:

    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}

    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: platform-auth
          uri: lb://platform-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #system 模块
        - id: platform-system
          uri: lb://platform-system
          predicates:
            - Path=/system/**
        # 固定路由转发配置 无修改
        - id: openapi
          uri: lb://pig-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs

gateway:
  encode-key: 'eXTqsEKIPRsksJSK'
  ignore-clients:
    - swagger
  services: { "platform-system": "/system" }

# spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
      client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      scope: server
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs
        - /actuator/**
