server:

  port: ${PORT_PLATFORM_GATEWAY:8101}

spring:
  profiles:
    active: ${RUN_MODE:local}
  main:
    allow-bean-definition-overriding: true
  application:
    name: platform-gateway

  config:
    import:
      - nacos:global-configuration.yaml?refresh=true
      - nacos:rabbitmq.yaml
      - nacos:redis.yaml
      - nacos:jasypt.yaml
      - nacos:platform-system-rabbit-mq-queue.yaml
      - nacos:sa-token.yaml
      - nacos:gateway.yaml?refresh=true

  cloud:

    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}

    gateway:
      httpclient:
        connect-timeout: 200
        response-timeout: 10s
        pool:
          max-idle-time: 10s
          eviction-interval: 30s
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true

    sentinel:
      eager: true
      filter:
        enabled: false
      datasource:
        # 网关api分组
        gw-api-group:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: ${spring.cloud.nacos.config.group}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            dataId: ${spring.application.name}-api-group.json
            data-type: json
            rule-type: gw-api-group
        # 网关流控规则
        gw-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: ${spring.cloud.nacos.config.group}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            dataId: ${spring.application.name}-flow-rule.json
            data-type: json
            rule-type: gw-flow
        # 降级规则
        degrade:
          nacos:
            server-addr: ${spring.cloud.nacos.config.server-addr}
            namespace: ${spring.cloud.nacos.config.namespace}
            groupId: ${spring.cloud.nacos.config.group}
            username: ${spring.cloud.nacos.config.username}
            password: ${spring.cloud.nacos.config.password}
            dataId: ${spring.application.name}-degrade-rule.json
            data-type: json
            rule-type: degrade
        # 系统规则 有bug暂时不生效待修复
#        system:
#          nacos:
#            server-addr: ${spring.cloud.nacos.config.server-addr}
#            namespace: ${spring.cloud.nacos.config.namespace}
#            groupId: ${spring.cloud.nacos.config.group}
#            username: ${spring.cloud.nacos.config.username}
#            password: ${spring.cloud.nacos.config.password}
#            dataId: ${spring.application.name}-system-rule.json
#            data-type: json
#            rule-type: system
