server:

  port: ${PORT_GATEWAY:8301}

spring:

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  main:
    allow-bean-definition-overriding: true

  application:
    name: platform-gateway

  config:
    import:
      - nacos:global-configuration.yaml
      - nacos:${spring.application.name}.yaml

  cloud:

    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}

    gateway:
      loadbalancer:
        use404: true
      default-filters:
        - StripPrefix=1
      discovery:
        locator:
          enabled: true
      routes:
        # 认证中心
        - id: platform-auth
          uri: lb://platform-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeGatewayFilter
            # 前端密码解密
            - PasswordDecoderFilter
        #system 模块
        - id: platform-system
          uri: lb://platform-system
          predicates:
            - Path=/system/**
        # 固定路由转发配置 无修改
        - id: openapi
          uri: lb://pig-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/$\{path}/v3/api-docs

  rabbitmq:
    host: ${RABBIT_MQ_HOST:127.0.0.1}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:root}
    password: ${RABBIT_MQ_PASSWORD:123456}
    virtual-host: /${NACOS_NAMESPACE:dev}
    # 手动提交消息
    listener:
      simple:
        #消息必须手动确认
        acknowledge-mode: manual
        #限制每次发送一条数据。
        prefetch: 1
    publisher-returns: true
    publisher-confirm-type: simple

  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      lettuce:
        pool:
          min-idle: 8
          max-idle: 500
          max-active: 2000
          max-wait: 10000
      timeout: 5000

logging:
  level:
    com.zclcs: info

my:
  redis-cache-prefix: '${NACOS_NAMESPACE:dev}:'

gateway:
  encode-key: 'eXTqsEKIPRsksJSK'
  ignore-clients:
    - swagger
  services: { "platform-system": "/system" }

# spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
      client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      scope: server
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs
        - /actuator/**

# 加解密根密码
jasypt:
  encryptor:
    password: zclcs
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
