gateway:
  encode-key: 'eXTqsEKIPRsksJSK'
  need-check-valid-code-urls:
    - "/login/token/byUsername"
    - "/login/token/byMobile"
  ignore-urls:
    - "/system/login/token/byUsername"
    - "/system/login/token/byMobile"

