server:
  port: ${PORT_DATA_SYNC:7101}
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: third-part-database-sync

  datasource:
    nacos:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:${SPRING_DATASOURCE_PLATFORM:mysql}://${MYSQL_SERVICE_HOST:127.0.0.1}:${MYSQL_SERVICE_PORT:3306}/${MYSQL_SERVICE_DB_NAME:third_part_nacos}?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
      username: ${MYSQL_SERVICE_USER:root}
      password: ${MYSQL_SERVICE_PASSWORD:root}
    xxl-job:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:${SPRING_DATASOURCE_PLATFORM:mysql}://${MYSQL_SERVICE_HOST:127.0.0.1}:${MYSQL_SERVICE_PORT:3306}/${XXL_JOB_DB_NAME:third_part_xxl_job}?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai
      username: ${MYSQL_SERVICE_USER:root}
      password: ${MYSQL_SERVICE_PASSWORD:root}

my:
  nacos-namespace: ${NACOS_NAMESPACE:dev}
