server:
  port: ${PORT_DATA_SYNC:7101}
spring:
  application:
    name: third-part-database-sync

  datasource:
    nacos:
      driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
      url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${NACOS_NAMESPACE:dev}_nacos?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
      username: ${DATASOURCE_USERNAME:root}
      password: ${DATASOURCE_PASSWORD:root}
    xxl-job:
      driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
      url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${NACOS_NAMESPACE:dev}_xxl_job?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
      username: ${DATASOURCE_USERNAME:root}
      password: ${DATASOURCE_PASSWORD:root}

  cloud:
    nacos:
      config:
        namespace: ${NACOS_NAMESPACE:dev}
