server:
  port: ${PORT_PLATFORM_MAINTENANCE:8202}

spring:
  application:
    name: platform-maintenance

  cloud:
    nacos:
      config:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

  config:
    import:
      - nacos:hikari.yaml
      - nacos:openfeign.yaml
      - nacos:rabbitmq.yaml
      - nacos:redis.yaml
      - nacos:swagger-${spring.profiles.active}.yaml
      - nacos:system-dict.yaml
      - nacos:xxl-job.yaml
      - nacos:platform-system-rabbit-mq-queue.yaml

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:127.0.0.1}:${DATASOURCE_PORT:3306}/${spring.cloud.nacos.config.namespace}_platform_system?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_ROOT_USERNAME:root}
    password: ${DATASOURCE_ROOT_PASSWORD:123456}

management:
  endpoints:
    web:
      exposure:
        include: '*'

# spring security 配置
security:
  oauth2:
    client:
      client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
      client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
      scope: server
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs

my:
  xxl:
    job:
      enable: false