server:
  port: ${PORT_PLATFORM_MAINTENANCE:8301}

spring:
  profiles:
    active: ${RUN_MODE:local}
  application:
    name: platform-maintenance

  cloud:
    refresh:
      enabled: ${CONFIG_REFRESH:false}
    nacos:
      config:
        server-addr: ${NACOS_HOST:192.168.33.10}:${NACOS_PORT:8848}
        namespace: ${NACOS_NAMESPACE:dev}
        group: DEFAULT_GROUP
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      discovery:
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
        group: DEFAULT_GROUP
        username: ${spring.cloud.nacos.config.username}
        password: ${spring.cloud.nacos.config.password}

  config:
    import:
      - optional:nacos:global-configuration.yaml
      - optional:nacos:tomcat.yaml
      - optional:nacos:openfeign.yaml
      - optional:nacos:hikari.yaml
      - optional:nacos:rabbitmq.yaml
      - optional:nacos:redis.yaml
      - optional:nacos:jasypt.yaml
      - optional:nacos:system-dict.yaml
      - optional:nacos:minio.yaml
      - optional:nacos:platform-system-rabbit-mq-queue.yaml
      - optional:nacos:sa-token.yaml

  datasource:
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    url: jdbc:${DATASOURCE_DB_TYPE:mysql}://${DATASOURCE_HOST:192.168.33.10}:${DATASOURCE_PORT:3306}/${spring.cloud.nacos.config.namespace}_platform_system?${DATASOURCE_PARAM:useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=Asia/Shanghai}
    username: ${DATASOURCE_ROOT_USERNAME:root}
    password: ${DATASOURCE_ROOT_PASSWORD:123456}

platform-maintenance:
  power-job-host: ${POWER_JOB_HOST:192.168.33.10}
  power-job-port: ${POWER_JOB_PORT:7700}
