version: '3'

services:
  seata:
    image: ${CLOUD_DEPOSITORY_IP_PORT}/library/seata:1.5.2
    container_name: ${NACOS_NAMESPACE}_seata
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      STORE_MODE: db
      # 指定seata服务启动端口
      SEATA_PORT: ${SEATA_PORT}
      # 注册到nacos上的ip。客户端将通过该ip访问seata服务。
      # 注意公网ip和内网ip的差异。
      SEATA_IP: ${LOCAL_IP}
    volumes:
      - "./seata/config/application.yml:/seata-server/resources/application.yml"
      - "./seata/logs:/logs/seata"
    healthcheck:
      test: [ "CMD", "nc", "-vz", "${LOCAL_HOST_IP}", "${SEATA_MANAGER_PORT}" ]
      interval: ${DOCKER_HEALTHCHECK_INTERVAL}
      timeout: ${DOCKER_HEALTHCHECK_TIMEOUT}
      retries: ${DOCKER_HEALTHCHECK_RETRIES}
    env_file: .env